version: "3.8"

services:
  nextjs:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: pocketnext-nextjs
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_POCKETBASE_URL=http://pocketbase:8090
    depends_on:
      - pocketbase

  pocketbase:
    build:
      context: ./pb
      dockerfile: Dockerfile
      args:
        - PB_VERSION=${PB_VERSION:-0.25.8}
    container_name: pocketnext-pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - pb_data:/pb/pb_data
      - ./pb/pb_migrations:/pb/pb_migrations
      - ./pb/pb_hooks:/pb/pb_hooks
    environment:
      - PB_ADMIN_EMAIL=${PB_ADMIN_EMAIL:-}
      - PB_ADMIN_PASSWORD=${PB_ADMIN_PASSWORD:-}

volumes:
  pb_data:
    driver: local
